name: Python Application Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --cov=app test_app.py  # Run tests with coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
            token: ${{ secrets.CODECOV_TOKEN }}  # Add Codecov token as a GitHub secret

      - name: Slack Notification
        if: failure()
        uses: slackapi/slack-github-action@v1.16.0
        with:
            channel-id: "C0809H4JJ8H"
            slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
            text: "GitHub Action failed on ${{ github.repository }} at ${{ github.ref }}"